### ISSUE TITLE
Close Aktion loses Focus

### ISSUE THREAD

**Issue by jlnrrg** [ukieTux/animated_search_bar#4]
When using the close Aktion right to the input field, the searchbar loses focus.
I personally would understand the close button more as a clear button for the search field, thus expecting the search bar to be still in focus to input the next search.
How is your opinion for this?

**Comment by Lzyct** [comment]
Yup, it's good Idea.
If search field is not empty, when user press X icon. The search field will be clear, then if search field is empty it's should be hide searchBar

**Comment by Lzyct** [comment]
You can check the latest version in pub.dev for new update
Thanks

**Comment by jlnrrg** [comment]
It works very well. Thank you for the fast and brilliant implementation :+1:
